/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Trigger Google OAuth login flow
         * @description Direct browser link to start Google single sign-on.
         */
        get: operations["AuthController_googleAuth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google OAuth callback handler
         * @description Receives Google callback code, creates/links user, and redirects to web app.
         */
        get: operations["AuthController_googleAuthRedirect"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current User Identity
         * @description Protected test route to verify your JWT token in Swagger.
         */
        get: operations["AuthController_getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bootstrap Organization & Assign Caller as Owner
         * @description Atomically provisions an organization, default location, canonical RBAC permissions/roles, and logs an audit record.
         */
        post: operations["OrganizationController_setup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all positions within an organization */
        get: operations["PositionsController_findAllByOrg"];
        put?: never;
        /** Create a new job position for an organization */
        post: operations["PositionsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/positions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get details for a specific position */
        get: operations["PositionsController_findOne"];
        put?: never;
        post?: never;
        /** Delete a position (blocked if active shifts exist) */
        delete: operations["PositionsController_remove"];
        options?: never;
        head?: never;
        /** Update a position name or hourly rate */
        patch: operations["PositionsController_update"];
        trace?: never;
    };
    "/organizations/{orgId}/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all employees with roles and assigned positions */
        get: operations["EmployeesController_findAll"];
        put?: never;
        /** Onboard a new employee */
        post: operations["EmployeesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{orgId}/employees/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Offboard an employee from the organization */
        delete: operations["EmployeesController_offboard"];
        options?: never;
        head?: never;
        /** Update employee profile and role/scope assignment */
        patch: operations["EmployeesController_updateProfile"];
        trace?: never;
    };
    "/organizations/{orgId}/employees/{userId}/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Reassign positions to an employee */
        patch: operations["EmployeesController_assignPositions"];
        trace?: never;
    };
    "/scheduling/shifts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new shift
         * @description Creates a draft shift in scheduled status with cross-location conflict validation and max duration verification.
         */
        post: operations["SchedulingController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scheduling/locations/{locationId}/shifts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List raw shifts by location and date range
         * @description Retrieves flat shift records filtered by date range for a specific location.
         */
        get: operations["SchedulingController_findByLocation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scheduling/locations/{locationId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish location roster
         * @description Transitions all scheduled shifts within a date window to published status.
         */
        post: operations["SchedulingController_publishRoster"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scheduling/locations/{locationId}/grid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch schedule grid matrix (Sling-style)
         * @description Returns pre-computed schedule rows grouped by employee or position, with real-time labor totals, open shifts, overtime, and leadership compliance flags.
         */
        get: operations["SchedulingController_getGrid"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scheduling/shifts/{id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Drag & drop shift move
         * @description Reassigns a shift to a new user, position, date, or time slot with overlap validation.
         */
        patch: operations["SchedulingController_moveShift"];
        trace?: never;
    };
    "/scheduling/shifts/{id}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Duplicate shift
         * @description Copies a shift template to a target date, time, or employee as a draft shift.
         */
        post: operations["SchedulingController_duplicateShift"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scheduling/locations/{locationId}/operating-hours": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Configure store operating hours & leadership staffing rule
         * @description Sets daily open/close hours and configures whether a Lead/Manager must be on duty continuously.
         */
        put: operations["SchedulingController_updateOperatingHours"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scheduling/locations/{locationId}/quick-drop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Quick-drop employee onto calendar day
         * @description Instantly creates a shift starting at store open time for a date by dragging an employee chip onto a day.
         */
        post: operations["SchedulingController_quickDrop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scheduling/locations/{locationId}/copy-week": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 1-Click Copy Week Schedule
         * @description Clones entire previous week roster into the future week in draft status, checking for conflicts.
         */
        post: operations["SchedulingController_copyWeek"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scheduling/trades/claim/{shiftId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Claim an open shift
         * @description Assigns an open shift to the requesting employee if they hold the qualification and have no overlapping shifts.
         */
        post: operations["ShiftTradeController_claimOpenShift"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scheduling/trades/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request shift swap or drop
         * @description Creates a request to swap a shift with a coworker or drop it to the open shift pool.
         */
        post: operations["ShiftTradeController_requestTrade"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scheduling/trades/{tradeId}/peer-respond": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Accept or decline a peer swap request
         * @description The target employee can accept or decline a 1-to-1 swap request before it routes to management.
         */
        put: operations["ShiftTradeController_peerRespond"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scheduling/trades/{tradeId}/manager-review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Manager approval or rejection of a shift trade/drop
         * @description Atomically executes shift reassignment upon approval and records an audit log.
         */
        put: operations["ShiftTradeController_managerReview"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scheduling/trades/locations/{locationId}/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List pending trade approvals for a store
         * @description Retrieves all trade requests awaiting manager sign-off for a specific location.
         */
        get: operations["ShiftTradeController_getPendingTrades"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/time-off": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request time off
         * @description Creates a pending time-off request for the authenticated employee at a given location.
         */
        post: operations["TimeOffController_createRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/time-off/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List my time-off requests
         * @description Returns the authenticated employee's own time-off history, newest first.
         */
        get: operations["TimeOffController_listMine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/time-off/{requestId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Cancel a pending request
         * @description Withdraws a request the employee made themselves, only while it is still pending.
         */
        delete: operations["TimeOffController_cancelRequest"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/time-off/locations/{locationId}/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List pending time-off requests for a location
         * @description Manager-facing queue of requests awaiting review at this location.
         */
        get: operations["TimeOffController_getPendingForLocation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/time-off/{requestId}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Approve or deny a time-off request
         * @description Manager review action; records an audit log entry and notifies the requesting employee.
         */
        put: operations["TimeOffController_reviewRequest"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/time-tracking/locations/{locationId}/coordinates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Configure store GPS coordinates & geofence radius
         * @description Sets the latitude, longitude, and allowed proximity radius in meters for a location.
         */
        put: operations["TimeTrackingController_setLocationCoordinates"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/time-tracking/clock-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mobile GPS Clock-In
         * @description Verifies employee coordinates against the location geofence and matches against scheduled shifts.
         */
        post: operations["TimeTrackingController_clockIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/time-tracking/clock-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mobile GPS Clock-Out
         * @description Concludes active time entry, verifies departure location, and calculates final shift duration.
         */
        post: operations["TimeTrackingController_clockOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/time-tracking/locations/{locationId}/timesheets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get store timesheets for manager audit
         * @description Returns time entries with duration, labor costs, and geofence/punctuality flags.
         */
        get: operations["TimeTrackingController_getTimesheets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/time-tracking/entries/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Manager approve flagged or completed timesheet entry */
        put: operations["TimeTrackingController_approveTimeEntry"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/locations/{locationId}/labor-variance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Scheduled vs Actual Labor Cost Variance
         * @description Calculates planned roster costs vs actual GPS-verified clock times, including overtime and variance.
         */
        get: operations["AnalyticsController_getLaborVariance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payroll/locations/{locationId}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Calculate pay period summary
         * @description Aggregates hours, regular pay, overtime (1.5x over 40h), and gross wages for all employees.
         */
        get: operations["PayrollController_getSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payroll/locations/{locationId}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Payroll CSV
         * @description Generates a CSV file formatted for direct import into payroll software (Standard, Gusto, or ADP).
         */
        get: operations["PayrollController_exportCsv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SetupOrgDto: {
            /**
             * @description Legal or operating business name
             * @example Apex Logistics Inc.
             */
            organizationName: string;
            /**
             * @default UTC
             * @example America/Toronto
             */
            timezone: string;
            /**
             * @description Primary branch location name
             * @example Main Distribution Hub
             */
            primaryLocationName: string;
            /**
             * @description Physical address used for shift geofencing
             * @example 450 Conestoga Blvd, Cambridge, ON
             */
            address?: string;
        };
        CreatePositionDto: {
            /**
             * @description Organization UUID
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            orgId: string;
            /**
             * @description Name of the job role or position
             * @example Shift Supervisor
             */
            name: string;
            /**
             * @description Default base hourly rate for this position
             * @example 22.5
             */
            hourlyRate?: number;
        };
        UpdatePositionDto: {
            /**
             * @description Name of the job role or position
             * @example Shift Supervisor
             */
            name?: string;
            /**
             * @description Default base hourly rate for this position
             * @example 22.5
             */
            hourlyRate?: number;
        };
        CreateEmployeeDto: {
            /**
             * @description Organization UUID
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            orgId: string;
            /**
             * @description Work or personal email
             * @example alex.worker@example.com
             */
            email: string;
            /**
             * @description Full legal name
             * @example Alex Mercer
             */
            fullName: string;
            /**
             * @description Contact phone number (E.164 format)
             * @example +15195550199
             */
            phone?: string;
            /**
             * @description Role name: Employee, Manager, or Admin
             * @default Employee
             * @example Employee
             */
            roleName: string;
            /**
             * @description Role assignment scope
             * @example location
             * @enum {string}
             */
            scopeType: "organization" | "location";
            /**
             * @description UUID of the target Location or Organization
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            scopeId: string;
            /**
             * @description Array of Position UUIDs to assign to this employee
             * @example [
             *       "3fa85f64-5717-4562-b3fc-2c963f66afa6"
             *     ]
             */
            positionIds?: string[];
        };
        UpdateEmployeeProfileDto: {
            /**
             * @description Organization UUID
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            orgId?: string;
            /**
             * @description Work or personal email
             * @example alex.worker@example.com
             */
            email?: string;
            /**
             * @description Full legal name
             * @example Alex Mercer
             */
            fullName?: string;
            /**
             * @description Contact phone number (E.164 format)
             * @example +15195550199
             */
            phone?: string;
            /**
             * @description Role name: Employee, Manager, or Admin
             * @default Employee
             * @example Employee
             */
            roleName: string;
            /**
             * @description Role assignment scope
             * @example location
             * @enum {string}
             */
            scopeType?: "organization" | "location";
            /**
             * @description UUID of the target Location or Organization
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            scopeId?: string;
            /**
             * @description Array of Position UUIDs to assign to this employee
             * @example [
             *       "3fa85f64-5717-4562-b3fc-2c963f66afa6"
             *     ]
             */
            positionIds?: string[];
        };
        AssignPositionsDto: {
            /**
             * @description Complete list of Position UUIDs assigned to this employee
             * @example [
             *       "3fa85f64-5717-4562-b3fc-2c963f66afa6"
             *     ]
             */
            positionIds: string[];
        };
        CreateShiftDto: {
            /**
             * @description Location UUID
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            locationId: string;
            /**
             * @description Position UUID
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            positionId?: string;
            /**
             * @description Assigned User UUID (omit for open claimable shifts)
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            assignedUserId?: string;
            /**
             * @description Shift start timestamp in ISO-8601 UTC
             * @example 2026-09-15T09:00:00Z
             */
            startTime: string;
            /**
             * @description Shift end timestamp in ISO-8601 UTC
             * @example 2026-09-15T17:00:00Z
             */
            endTime: string;
        };
        PublishRosterDto: {
            /**
             * @description Start of schedule window
             * @example 2026-09-14T00:00:00Z
             */
            startDate: string;
            /**
             * @description End of schedule window
             * @example 2026-09-20T23:59:59Z
             */
            endDate: string;
        };
        MoveShiftDto: {
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            targetUserId?: Record<string, never>;
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            targetPositionId?: Record<string, never>;
            /** @example 2026-09-16T09:00:00Z */
            newStartTime: string;
            /** @example 2026-09-16T17:00:00Z */
            newEndTime: string;
        };
        DuplicateShiftDto: {
            /** @example 2026-09-17T09:00:00Z */
            newStartTime: string;
            /** @example 2026-09-17T17:00:00Z */
            newEndTime: string;
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            targetUserId?: string;
        };
        UpdateLocationOperatingHoursDto: {
            /**
             * @example {
             *       "monday": {
             *         "isOpen": true,
             *         "open": "08:00",
             *         "close": "22:00"
             *       },
             *       "tuesday": {
             *         "isOpen": true,
             *         "open": "08:00",
             *         "close": "22:00"
             *       },
             *       "wednesday": {
             *         "isOpen": true,
             *         "open": "08:00",
             *         "close": "22:00"
             *       },
             *       "thursday": {
             *         "isOpen": true,
             *         "open": "08:00",
             *         "close": "22:00"
             *       },
             *       "friday": {
             *         "isOpen": true,
             *         "open": "08:00",
             *         "close": "23:00"
             *       },
             *       "saturday": {
             *         "isOpen": true,
             *         "open": "09:00",
             *         "close": "23:00"
             *       },
             *       "sunday": {
             *         "isOpen": true,
             *         "open": "10:00",
             *         "close": "18:00"
             *       }
             *     }
             */
            operatingHours: Record<string, never>;
            /**
             * @description Enforces that at least 1 Manager/TL/ATL must be on shift at all operating times
             * @example true
             */
            requireLeadershipOnDuty: boolean;
        };
        QuickDropShiftDto: {
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            userId: string;
            /**
             * @description YYYY-MM-DD date in store local timezone
             * @example 2026-09-15
             */
            date: string;
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            positionId?: string;
            /**
             * @description Shift duration in hours
             * @default 8
             * @example 8
             */
            durationHours: number;
        };
        CopyWeekDto: {
            /**
             * @description Source week start date (Monday)
             * @example 2026-09-07T00:00:00Z
             */
            sourceStartDate: string;
            /**
             * @description Target week start date (Monday)
             * @example 2026-09-14T00:00:00Z
             */
            targetStartDate: string;
            /**
             * @description If true, skips shifts that would cause an employee double-booking instead of failing
             * @default true
             * @example true
             */
            skipConflicts: boolean;
        };
        RequestShiftTradeDto: {
            /**
             * @description Shift you own and want to trade/drop
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            shiftId: string;
            /**
             * @example drop
             * @enum {string}
             */
            type: "swap" | "drop";
            /**
             * @description Target employee for 1-to-1 swap (omit if dropping to open pool)
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            targetUserId?: string;
            /**
             * @description The shift owned by target employee being swapped for
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            targetShiftId?: string;
            /** @example Doctor appointment conflict */
            reason?: string;
        };
        ReviewTradeDto: {
            /**
             * @example approve
             * @enum {string}
             */
            action: "approve" | "reject";
            /** @example Approved - coverage confirmed */
            reason?: string;
        };
        CreateTimeOffRequestDto: {
            /**
             * @description Location this request applies to
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            locationId: string;
            /**
             * @description First day off (inclusive), YYYY-MM-DD
             * @example 2026-10-01
             */
            startDate: string;
            /**
             * @description Last day off (inclusive), YYYY-MM-DD
             * @example 2026-10-03
             */
            endDate: string;
            /** @example Family wedding out of town */
            reason?: string;
        };
        ReviewTimeOffDto: {
            /**
             * @example approve
             * @enum {string}
             */
            action: "approve" | "deny";
            /** @example Approved - coverage confirmed */
            reason?: string;
        };
        SetLocationCoordinatesDto: {
            /** @example 43.3616 */
            latitude: number;
            /** @example -80.3144 */
            longitude: number;
            /**
             * @description Acceptable radius in meters
             * @default 150
             * @example 150
             */
            geofenceRadiusMeters: number;
        };
        ClockInDto: {
            /**
             * @description Location UUID
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            locationId: string;
            /**
             * @description GPS Latitude
             * @example 43.3616
             */
            latitude: number;
            /**
             * @description GPS Longitude
             * @example -80.3144
             */
            longitude: number;
            /**
             * @description Linked Shift UUID
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            shiftId?: string;
            /** @example Covering for John Doe */
            notes?: string;
        };
        ClockOutDto: {
            /**
             * @description GPS Latitude
             * @example 43.3616
             */
            latitude: number;
            /**
             * @description GPS Longitude
             * @example -80.3144
             */
            longitude: number;
            /** @example Store locked and alarms armed */
            notes?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_googleAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_googleAuthRedirect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirects to frontend auth callback. */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrganizationController_setup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupOrgDto"];
            };
        };
        responses: {
            /** @description Organization workspace initialized successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed (e.g., invalid IANA timezone). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or expired JWT Bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User already owns/administers an organization. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PositionsController_findAllByOrg: {
        parameters: {
            query: {
                orgId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of positions with assignment/shift counts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PositionsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePositionDto"];
            };
        };
        responses: {
            /** @description Position created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User does not belong to target organization */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Position with this name already exists in org */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PositionsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Position details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Position not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PositionsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Position deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Cannot delete: active shifts depend on it */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PositionsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePositionDto"];
            };
        };
        responses: {
            /** @description Position updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Position name conflicts with existing entry */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmployeesController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmployeesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEmployeeDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmployeesController_offboard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmployeesController_updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEmployeeProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmployeesController_assignPositions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignPositionsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SchedulingController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateShiftDto"];
            };
        };
        responses: {
            /** @description Shift successfully created in scheduled state. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failure or duration exceeds 24 hours. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User lacks authorization for this location. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Location, position, or assigned user does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Employee already has an overlapping shift. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SchedulingController_findByLocation: {
        parameters: {
            query?: {
                startDate?: string;
                endDate?: string;
            };
            header?: never;
            path: {
                /** @description Target Location UUID */
                locationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Flat list of shifts for the window. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SchedulingController_publishRoster: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Target Location UUID */
                locationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishRosterDto"];
            };
        };
        responses: {
            /** @description Roster published successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SchedulingController_getGrid: {
        parameters: {
            query: {
                startDate: string;
                endDate: string;
                groupBy?: "employee" | "position";
            };
            header?: never;
            path: {
                /** @description Target Location UUID */
                locationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pre-computed grid payload. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SchedulingController_moveShift: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Target Shift UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveShiftDto"];
            };
        };
        responses: {
            /** @description Shift moved successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Target user already scheduled at another location. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SchedulingController_duplicateShift: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Source Shift UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DuplicateShiftDto"];
            };
        };
        responses: {
            /** @description Shift duplicated successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SchedulingController_updateOperatingHours: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                locationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLocationOperatingHoursDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SchedulingController_quickDrop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                locationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuickDropShiftDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SchedulingController_copyWeek: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                locationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CopyWeekDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ShiftTradeController_claimOpenShift: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Open Shift UUID */
                shiftId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Shift claimed successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing position qualification. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Shift already claimed or conflicting shift exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ShiftTradeController_requestTrade: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestShiftTradeDto"];
            };
        };
        responses: {
            /** @description Trade request created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ShiftTradeController_peerRespond: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ShiftTrade UUID */
                tradeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ShiftTradeController_managerReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ShiftTrade UUID */
                tradeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewTradeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ShiftTradeController_getPendingTrades: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Location UUID */
                locationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TimeOffController_createRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTimeOffRequestDto"];
            };
        };
        responses: {
            /** @description Request created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Overlaps an existing pending/approved request. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TimeOffController_listMine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TimeOffController_cancelRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description TimeOffRequest UUID */
                requestId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TimeOffController_getPendingForLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Location UUID */
                locationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TimeOffController_reviewRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description TimeOffRequest UUID */
                requestId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewTimeOffDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TimeTrackingController_setLocationCoordinates: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Location UUID */
                locationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetLocationCoordinatesDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TimeTrackingController_clockIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClockInDto"];
            };
        };
        responses: {
            /** @description Clock-in recorded. Returns entry status (active or flagged). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Employee is already clocked in. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TimeTrackingController_clockOut: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClockOutDto"];
            };
        };
        responses: {
            /** @description Clock-out recorded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No active clock-in found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TimeTrackingController_getTimesheets: {
        parameters: {
            query: {
                startDate: string;
                endDate: string;
            };
            header?: never;
            path: {
                /** @description Location UUID */
                locationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TimeTrackingController_approveTimeEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description TimeEntry UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AnalyticsController_getLaborVariance: {
        parameters: {
            query: {
                /** @description Window start date (UTC) */
                startDate: string;
                /** @description Window end date (UTC) */
                endDate: string;
            };
            header?: never;
            path: {
                /** @description Location UUID */
                locationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PayrollController_getSummary: {
        parameters: {
            query: {
                /** @description Pay period start timestamp (UTC) */
                startDate: string;
                /** @description Pay period end timestamp (UTC) */
                endDate: string;
                format?: "standard" | "gusto" | "adp";
            };
            header?: never;
            path: {
                /** @description Location UUID */
                locationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregated payroll numbers per employee. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PayrollController_exportCsv: {
        parameters: {
            query: {
                /** @description Pay period start timestamp (UTC) */
                startDate: string;
                /** @description Pay period end timestamp (UTC) */
                endDate: string;
                format?: "standard" | "gusto" | "adp";
            };
            header?: never;
            path: {
                /** @description Location UUID */
                locationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
